### ISSUE TITLE
Add PID for SteelSeries Rival 5

### ISSUE THREAD

**Issue by timpa009** [DarthAffe/RGB.NET#280]
The SteelSeries Rival 5 is a 10-Zone mouse with PID 0x183C

**Comment by DarthAffe** [comment]
Hey, are you able to test a custom build? The steelseries docs don't include a 10-zone device type (only eight and twelve) so I'm not sure if it just works with 10 or needs to be one of them.
[RGB.NET.Devices.SteelSeries.zip](https://github.com/DarthAffe/RGB.NET/files/10147383/RGB.NET.Devices.SteelSeries.zip)

**Comment by timpa009** [comment]
Sadly that does not work. It throws up an error whenever I try to reload the plugin and fails to load the plugin at all:

`Artemis.Core.ArtemisPluginException: Plugin load timeout
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 174
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 721
   at Artemis.Core.Services.PluginManagementService.EnablePlugin(Plugin plugin, Boolean saveState, Boolean ignorePluginLock) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 470
   at Artemis.UI.Screens.Plugins.PluginSettingsViewModel.<>c__DisplayClass13_0.<ExecuteReload>b__1() in D:\a\1\s\Artemis\src\Artemis.UI\Screens\Plugins\PluginSettingsViewModel.cs:line 47
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Artemis.UI.Screens.Plugins.PluginSettingsViewModel.ExecuteReload() in D:\a\1\s\Artemis\src\Artemis.UI\Screens\Plugins\PluginSettingsViewModel.cs:line 47`

**Comment by DarthAffe** [comment]
Could you run all of them and check what happens and if/which of them works? (They should just color all leds of the mouse red.)
[SteelSeriesTest.zip](https://github.com/DarthAffe/RGB.NET/files/10211507/SteelSeriesTest.zip)

**Comment by timpa009** [comment]
Nothing...
My keyboard and mousemat change to red (both also SteelSeries) but my mouse doesn't react even a tiny bit from any of these...

**Comment by DarthAffe** [comment]
Honstely I don't really know what to do. The SDK docs doesn't state anything about that case (10-zone devices simply don't exist there) - does it work with any other software with steelseries sdk support?

**Comment by DarthAffe** [comment]
fixed with #282
thanks for running all the tests :)
