### ISSUE TITLE
Aura crash when setting device mode

### ISSUE THREAD

**Issue by arduano** [DarthAffe/RGB.NET#29]
Line:
`surface.LoadDevices(AsusDeviceProvider.Instance);`
Error:
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`
Trace:
```   at RGB.NET.Devices.Asus.Native._AsusSDK.SetMbMode(IntPtr handle, Int32 mode)
   at RGB.NET.Devices.Asus.AsusDeviceProvider.Initialize(RGBDeviceType loadFilter, Boolean exclusiveAccessIfPossible, Boolean throwExceptions)
   at RGB.NET.Core.RGBSurface.LoadDevices(IRGBDeviceProvider deviceProvider, RGBDeviceType loadFilter, Boolean exclusiveAccessIfPossible, Boolean throwExceptions)
   at RGB_Unity.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in G:\Personal\2018\Asus Aura\RGB Unity\MainWindow.xaml.cs:line 37
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

My motherboard is ASUS ROG Strix x399-E.
When I run the official demo program for the SDK (the one that comes inside the asus aura sdk zip file), it also crashes when I select "motherboard". The GPU demo works just fine though. I don't have an aura mouse/keyboard. But I do have Trident Z RGB ram, which also works with aura.

Is this just me?

**Comment by arduano** [comment]
Changed the line to
`surface.LoadDevices(AsusDeviceProvider.Instance, RGBDeviceType.GraphicsCard); `
The error stays the same but in the trace it's `at RGB.NET.Devices.Asus.Native._AsusSDK.SetGPUMode(IntPtr handle, Int32 mode)`

so it's not just my mobo's issue

**Comment by DarthAffe** [comment]
https://rog.asus.com/forum/showthread.php?97754-Access-Violation-Wrong-EnumerateMB-Result

**Comment by arduano** [comment]
Just in case, here's my full RGB specs:
mobo: ASUS ROG Strix x399-E
GPU: ASUS ROG Strix 1080ti (the actual GPU chipset doesn't matter  I think though)
RAM: G.Skill Trident Z RGB 3200Mhz Memory AMD (seems like it's not picked up when filtering by `RGBDeviceType.DRAM`, even though aura is supposed to support it, but that's probably a different issue)
