### ISSUE TITLE
Corsair Legacy, System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by Aytackydln** [DarthAffe/RGB.NET#346]
One of Aurora users had this exception. Sorry I am not able to make PR for a solution.

Device provider Corsair (RGB.NET) threw exception
System.ArgumentException: An item with the same key has already been added. Key: Invalid
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at RGB.NET.Devices.CorsairLegacy.CorsairCustomRGBDevice.InitializeLayout()
   at RGB.NET.Devices.CorsairLegacy.CorsairLegacyDeviceProvider.LoadDevices()+MoveNext()
   at RGB.NET.Core.AbstractRGBDeviceProvider.GetLoadedDevices(RGBDeviceType loadFilter)
   at RGB.NET.Core.AbstractRGBDeviceProvider.Initialize(RGBDeviceType loadFilter, Boolean throwExceptions)

**Comment by DarthAffe** [comment]
Which device is that? Normally I'd not expect to be Invalid-Leds present at all Oo

**Comment by AKBoy14** [comment]
Hi, I believe he's talking about me since he send me this link, I believe it's more easy if I show you

![Corsair RGB](https://github.com/DarthAffe/RGB.NET/assets/27347178/d01fa2b4-d8e4-4ffc-8a9c-b28c15b41b8d)

**Comment by DarthAffe** [comment]
I think this is causes by a wrong configuration in iCUE (iirc you have to configure somewhere what is attached to the hubs).
But I'll add a fx to ignore Invalid leds. That way it won't crash, but also not be able to controll them.

**Comment by AKBoy14** [comment]
I know that the QX fans are not recognized, so they won't turn on with aurora, but everything else worked for me the first time, after that, it just show that message.
